### Create comment
POST http://localhost:4000/api/comment/idea/7944df83-5ead-4d0d-bac7-2283d47d6ccd
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwN2MxOGE3LTg3MWMtNDcwMS04ODNjLTI3MmYwYzQ1YzdmMCIsInVzZXJuYW1lIjoidXNlcm5hbWU0MzMiLCJpYXQiOjE2NDM2MDY0MDEsImV4cCI6MTY0NDIxMTIwMX0.fOKug3o6BP6roH1O5x4IDHyoTuuWLYV9UvxCYfpPff8
 
{
    "comment": "test" 
}

### GET comments by idea
GET http://localhost:4000/api/comment/368a12b1-4468-4afb-9cea-bf293bb01ef9

{
    "comment": "test" 
}

### GET user by id
GET http://localhost:4000/api/comment/user/8ea48570-f0c8-4b0c-8c9e-998bd08f7d1d

### GET user by idea
GET http://localhost:4000/api/comment/idea/7944df83-5ead-4d0d-bac7-2283d47d6ccd

### DELETE comments by idea
DELETE http://localhost:4000/api/comment/368a12b1-4468-4afb-9cea-bf293bb01ef9

{
    "comment": "test" 
}