### Find all users
GET http://localhost:4000/api/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZWRiZDliLWU4MDAtNGQ5NS04NGQxLTM5N2Y2M2ZkZjEzMCIsInVzZXJuYW1lIjoidXNlcm5hbWUyIiwiaWF0IjoxNjQzNDk2MTU1LCJleHAiOjE2NDQxMDA5NTV9.lOyS1e4rbuCTL5QzguFNIyd9BPdFh1s87quoUdVLRJs

### login user
POST http://localhost:4000/login
content-type: application/json

{
  "username": "username",
  "password": "password"
}

### Register
POST http://localhost:4000/register
content-type: application/json

{
  "username": "username2",
  "password": "password"
}