### Find all users
GET http://localhost:4000/api/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyOTEzYjMyLWU5MWEtNDgyNi04MzM5LTg1NTIzYzI1ODlmYiIsInVzZXJuYW1lIjoidXNlcm5hbWU0IiwiaWF0IjoxNjQzNTEyODE1LCJleHAiOjE2NDQxMTc2MTV9.wG4j74CsteThkWUcKRgFjsuH_mC6NZkx-FCowGCD1p4

### login user
POST http://localhost:4000/login
content-type: application/json

{
  "username": "username43",
  "password": "password"
}

### Register
POST http://localhost:4000/register
content-type: application/json

{
  "username": "username433",
  "password": "password"
}