### Find a particular idea with a given ID
GET http://localhost:4000/idea/ce3a426e-4cf7-48d6-9c5a-4ece74c5c255

### Find all ideas
GET http://localhost:4000/idea

### Delete one idea
DELETE  http://localhost:4000/idea/ce3a426e-4cf7-48d6-9c5a-4ece74c5c255

### Create idea
POST http://localhost:4000/idea
content-type: application/json

{
  "idea": "test",
  "description": "test"
}

### Create idea
PUT http://localhost:4000/idea/ce3a426e-4cf7-48d6-9c5a-4ece74c5c255
content-type: application/json

{
    "description": "test3"
}


